### ISSUE TITLE
server crash?

### ISSUE THREAD

**Issue by Derek1256** [kuba6000/AE2-Web-Integration#2]
not sure if this is on my end or not but anytime i add it server seems to crash? (i also put it on a testing server to make sure it wasn't something else in the pack).

log:

[crash-2024-08-15_00.26.15-server.txt](https://github.com/user-attachments/files/16619947/crash-2024-08-15_00.26.15-server.txt)

the issue:
itll reach the state to transition to server started but in trying it crashes. server loads fine with just ae2

im assuming this is on my end but thought id make a issue anyway

**Comment by kuba6000** [comment]
@Derek1256 
This mod is based on [GTNH fork of AE2](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/) (maintained and frequently updated with new features fork of AE2) and I am not planning to make it work with original AE2 for 1.7.10 anytime soon

**Comment by Derek1256** [comment]
ah figured as much will switch over
